version: '2'
services:
    web:
        build: nginx
        ports:
            - "80:80"
        volumes:
            - ./www:/var/www
        depends_on:
            - php-fpm
        links:
            - php-fpm
    php-fpm:
        build: php-fpm
        volumes:
            - ./www:/var/www
        depends_on:
            - mysql
        links:
            - mysql
    mysql:
        image: mysql:5.5
        ports:
            - "3306:3306"
        environment:
            - MYSQL_ALLOW_EMPTY_PASSWORD=true
            - MYSQL_DATABASE=symfony